spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/mywarehouse
spring.datasource.username=ayachan0084
spring.datasource.password=nokiabl4c055
spring.jpa.hibernate.ddl-auto=update

