-- Drop the table if it exists to ensure a clean slate for each full test suite run
DROP TABLE IF EXISTS products CASCADE;

-- Create the products table with an auto-incrementing ID
CREATE TABLE products
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(255)   NOT NULL,
    price    NUMERIC(38, 2) NOT NULL, -- Matches BigDecimal mapping safely
    quantity INT            NOT NULL
);